# Generated by Django 3.2.7 on 2022-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('geo', models.CharField(max_length=155)),
            ],
        ),
    ]
