# Generated by Django 3.2.7 on 2022-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screem_name', models.CharField(max_length=155)),
                ('follower_count', models.IntegerField()),
                ('screen_name_base', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_name_base', models.CharField(max_length=155)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('geo', models.CharField(max_length=155)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
